name: Chat App CI/CD

on:
  push:
    branches: ["master", "main"]

env:
  NODE_VERSION: '20.x'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend with env
        run: |
          cd frontend
          npm run build
        env:
          CI: false
          VITE_API_URL: "https://chat.tuanhuy227.xyz/api"
          VITE_SOCKET_URL: "https://chat.tuanhuy227.xyz"
          VITE_STREAM_API_KEY: "pavaphavh3cc"

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          retention-days: 1

  deploy:
    needs: build-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Copy dist to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || '22' }}
          source: "frontend/dist/*"
          target: "/home/chat/frontend"
          rm: true

      - name: SSH to VPS and update code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || '22' }}
          script: |
            cd /home/chat/backend

            # Nếu chưa clone thì clone
            if [ ! -d ".git" ]; then
              git clone https://github.com/<your-user>/<your-repo>.git /home/chat
            else
              git pull
            fi

            cd backend
            npm ci

            sudo npm install -g pm2
            pm2 stop all || true
            pm2 start src/index.js --name "backend" 

            echo "✅ Deployment completed!"
